blueprint:
  name: Pensili cucina – presenza con timer 15/20/25 v5
  description: >
    Versione corretta: istanziabile.
  domain: automation

  input:
    presence_sensor:
      name: Sensore presenza
      selector:
        entity:
          domain: binary_sensor

    light_target:
      name: Luce pensili
      selector:
        entity:
          domain: light

    brightness_helper:
      name: Helper luminosità
      selector:
        entity:
          domain: input_number

    t_50:
      name: Minuti prima del 50%
      default: 15
      selector:
        number:
          min: 1
          max: 120

    t_1:
      name: Minuti prima dell'1%
      default: 20
      selector:
        number:
          min: 1
          max: 180

    t_off:
      name: Minuti prima di OFF
      default: 25
      selector:
        number:
          min: 1
          max: 240

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensor
    to: "on"
    id: occupato

  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    id: assenza

  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    for:
      minutes: !input t_50
    id: dim_50

  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    for:
      minutes: !input t_1
    id: dim_1

  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    for:
      minutes: !input t_off
    id: off_finale

action:
  - variables:
      light_target: !input light_target
      brightness_helper: !input brightness_helper

  - choose:

      - conditions:
          - condition: trigger
            id: assenza
          - condition: template
            value_template: >
              {{ states(brightness_helper) | int == 0
                 and states(light_target) == 'on' }}
        sequence:
          - service: input_number.set_value
            target:
              entity_id: "{{ brightness_helper }}"
            data:
              value: "{{ state_attr(light_target,'brightness') | int }}"

      - conditions:
          - condition: trigger
            id: dim_50
          - condition: template
            value_template: >
              {{ states(light_target) == 'on'
                 and states(brightness_helper) | int > 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              brightness: "{{ (states(brightness_helper) | int * 0.5) | int }}"

      - conditions:
          - condition: trigger
            id: dim_1
          - condition: template
            value_template: "{{ states(light_target) == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              brightness_pct: 1

      - conditions:
          - condition: trigger
            id: off_finale
          - condition: template
            value_template: "{{ states(light_target) == 'on' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_target }}"

      - conditions:
          - condition: trigger
            id: occupato
          - condition: template
            value_template: "{{ states(brightness_helper) | int > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              brightness: "{{ states(brightness_helper) | int }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ brightness_helper }}"
            data:
              value: 0
