alias: Pensili cucina - presenza e spegnimento automatico
description: Dimming progressivo con ripristino anche dopo blackout
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.cucina_presence
    to: "on"
    id: occupato

  - platform: state
    entity_id: binary_sensor.cucina_presence
    to: "off"
    id: non_occupato

  - platform: state
    entity_id: light.pensili_cucina
    from: "unavailable"
    to: "on"
    id: ritorno_corrente

action:
  - choose:

      # =========================
      # PRESENZA RILEVATA
      # =========================
      - conditions:
          - condition: trigger
            id: occupato
          - condition: template
            value_template: "{{ states('input_number.luminosita_pensili_cucina') | int > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.pensili_cucina
            data:
              transition: 2
              brightness: "{{ states('input_number.luminosita_pensili_cucina') | int }}"
          - service: input_number.set_value
            target:
              entity_id: input_number.luminosita_pensili_cucina
            data:
              value: 0

      # =========================
      # ASSENZA
      # =========================
      - conditions:
          - condition: trigger
            id: non_occupato
        sequence:

          # Salva luminosità iniziale (una sola volta)
          - if:
              - condition: template
                value_template: "{{ states('input_number.luminosita_pensili_cucina') | int == 0 }}"
              - condition: state
                entity_id: light.pensili_cucina
                state: "on"
            then:
              - service: input_number.set_value
                target:
                  entity_id: input_number.luminosita_pensili_cucina
                data:
                  value: "{{ state_attr('light.pensili_cucina', 'brightness') | int }}"

          # 15 min → 50%
          - delay: "00:15:00"
          - condition: state
            entity_id: binary_sensor.cucina_presence
            state: "off"
          - service: light.turn_on
            target:
              entity_id: light.pensili_cucina
            data:
              transition: 5
              brightness: >
                {{ (states('input_number.luminosita_pensili_cucina') | int * 0.5) | int }}

          # 20 min → 1%
          - delay: "00:05:00"
          - condition: state
            entity_id: binary_sensor.cucina_presence
            state: "off"
          - service: light.turn_on
            target:
              entity_id: light.pensili_cucina
            data:
              transition: 5
              brightness_pct: 1

          # 25 min → OFF
          - delay: "00:05:00"
          - condition: state
            entity_id: binary_sensor.cucina_presence
            state: "off"
          - service: light.turn_off
            target:
              entity_id: light.pensili_cucina

      # =========================
      # RITORNO CORRENTE
      # =========================
      - conditions:
          - condition: trigger
            id: ritorno_corrente
          - condition: template
            value_template: "{{ states('input_number.luminosita_pensili_cucina') | int > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.pensili_cucina
            data:
              transition: 2
              brightness: "{{ states('input_number.luminosita_pensili_cucina') | int }}"
