blueprint:
  name: Presenza → 50% → 1% → OFF con ripristino (robusto)
  description: >
    Dimming progressivo a 15/20/25 minuti e ripristino al rientro.
    Salva la luminosità iniziale e la ripristina anche dopo blackout (unavailable→on).
  domain: automation

  input:
    presence_sensor:
      name: Sensore presenza
      selector:
        entity:
          domain: binary_sensor

    light_target:
      name: Luce pensili
      selector:
        entity:
          domain: light

    brightness_helper:
      name: Helper luminosità (input_number)
      description: Deve essere 0 quando “vuoto”
      selector:
        entity:
          domain: input_number

mode: restart

trigger:
  - platform: state
    entity_id: !input presence_sensor
    to: "on"
    id: occupato

  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    id: non_occupato

  - platform: state
    entity_id: !input light_target
    from: "unavailable"
    to: "on"
    id: ritorno_corrente

action:
  - variables:
      presence_sensor: !input presence_sensor
      light_target: !input light_target
      brightness_helper: !input brightness_helper

  - choose:

      # =========================
      # PRESENZA: ripristina se c'è un valore salvato
      # =========================
      - conditions:
          - condition: trigger
            id: occupato
          - condition: template
            value_template: "{{ states(brightness_helper) | int > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              transition: 5
              brightness: "{{ states(brightness_helper) | int }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ brightness_helper }}"
            data:
              value: 0

      # =========================
      # ASSENZA: salva e fa dimming 15/20/25
      # =========================
      - conditions:
          - condition: trigger
            id: non_occupato
        sequence:
          # Salva luminosità iniziale una sola volta (pre-15 minuti)
          - if:
              - condition: template
                value_template: "{{ states(brightness_helper) | int == 0 }}"
              - condition: state
                entity_id: "{{ light_target }}"
                state: "on"
            then:
              - service: input_number.set_value
                target:
                  entity_id: "{{ brightness_helper }}"
                data:
                  value: "{{ state_attr(light_target, 'brightness') | int }}"

          # 15 min → 50% del valore salvato
          - delay: "00:15:00"
          - condition: state
            entity_id: "{{ presence_sensor }}"
            state: "off"
          - if:
              - condition: template
                value_template: "{{ states(brightness_helper) | int > 0 }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: "{{ light_target }}"
                data:
                  transition: 5
                  brightness: "{{ (states(brightness_helper) | int * 0.5) | int }}"

          # 20 min → 1%
          - delay: "00:05:00"
          - condition: state
            entity_id: "{{ presence_sensor }}"
            state: "off"
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              transition: 5
              brightness_pct: 1

          # 25 min → OFF
          - delay: "00:05:00"
          - condition: state
            entity_id: "{{ presence_sensor }}"
            state: "off"
          - service: light.turn_off
            target:
              entity_id: "{{ light_target }}"

      # =========================
      # RITORNO CORRENTE: ripristina al valore pre-15 se esiste
      # =========================
      - conditions:
          - condition: trigger
            id: ritorno_corrente
          - condition: template
            value_template: "{{ states(brightness_helper) | int > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light_target }}"
            data:
              transition: 2
              brightness: "{{ states(brightness_helper) | int }}"
